Implement merge protection for main branch
Add merge protection check for main branch.

Signed-off-by: Dave Skender <8432125+DaveSkender@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -107,6 +107,13 @@ jobs:
     needs: quick-check
 
     steps:
+
+      - name: Merge protection check
+        if: github.base_ref == 'main'
+        run: |
+          echo "::error title=Reverse merge prohibited::❌ Targeting 'main' from a maintenance branch is prohibited."
+          exit 1
+    
       - name: Checkout source
         uses: actions/checkout@v6
 
